# HTTP Server
[server]
    Address     = ":8200"
    openapiPath = "/api.json"
    swaggerPath = "/swagger"
    ServerRoot  = "./public/resource"
    ServerAgent = "arco-demo"
    LogPath     = "./data/log/gf-app/server"
    logStdout           = true               # 日志是否输出到终端。默认为true
    errorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    errorLogPattern     = "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    accessLogPattern    = "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
    DumpRouterMap    = true
    NameToUriType = 3
    maxHeaderBytes    = "20KB"
    clientMaxBodySize = "200MB"
    accessLogEnabled    = true              # 是否记录访问日志。默认为false
    errorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
    PProfEnabled     = false                 # 是否开启PProf性能调试特性。默认为false
    debug               = true               # 是否是调试模式
    readTimeout         = "180s"             # 响应超时 3分钟

# Logger.
[logger]
    path        = "./data/log/gf-app"
    level       = "info"
    stdout      = true

# Database.
[database]
    [[database.default]]
        type = "mysql"
        link  = "arco-demo:arco-demo@tcp(127.0.0.1:3306)/arco-demo?charset=utf8mb4&parseTime=true&loc=Local"
        role = "master"
        timezone= "Asia/Shanghai"
        debug = true
    [[database.default]]
        type = "mysql"
        link  = "arco-demo:arco-demo@tcp(127.0.0.1:3306)/arco-demo?charset=utf8mb4&parseTime=true&loc=Local"
        role = "slave"
        timezone= "Asia/Shanghai"
        debug = true
    # Database logger.
    [database.logger]
        Path   = "./data/log/gf-app/sql"
        Level  = "debug"
        Stdout = false

# Redis数据库配置
[redis]
    open = true #是否开启 redis 缓存 若不开启使用gchache缓存方式
    [redis.default]
    host = "127.0.0.1:6379"
